# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='description',
            field=models.TextField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='frequency',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
